### ISSUE TITLE
Game freezes after first launch

### ISSUE THREAD

**Issue by dark159123** [phikal/ReGeX#32]
The game runs perfectly on the first launch after installation, but after closing the game and launching it again it simply hangs with an empty screen 
Nexus 6P running CopperheadOS
![screenshot_20161130-203937](https://cloud.githubusercontent.com/assets/18619090/20768352/e882d898-b73d-11e6-963b-df28dbf4232c.png)

The log seems to be in a loop. Here is the last part:
```
java.lang.IndexOutOfBoundsException: setSpan (5 ... 5) ends beyond length 0
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3401)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3441)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2714)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6080)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:68)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: Caused by: java.lang.IndexOutOfBoundsException: setSpan (5 ... 5) ends beyond length 0
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1265)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:677)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at android.text.Selection.setSelection(Selection.java:76)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at android.widget.EditText.setSelection(EditText.java:96)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at com.phikal.regex.Activities.GameActivity.onResume(Unknown Source)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6768)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3378)
11-30 20:41:34.683  5130  5130 E AndroidRuntime: 	... 12 more
11-30 20:41:34.685  5130  5130 E AndroidRuntime: Error reporting crash
11-30 20:41:34.685  5130  5130 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
11-30 20:41:34.685  5130  5130 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
11-30 20:41:34.685  5130  5130 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:615)
11-30 20:41:34.685  5130  5130 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5103)
11-30 20:41:34.685  5130  5130 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
11-30 20:41:34.685  5130  5130 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
11-30 20:41:34.685  5130  5130 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
11-30 20:41:34.685  5130  5130 I Process : Sending signal. PID: 5130 SIG: 9
11-30 20:41:34.731   877  2966 I ActivityManager: Process com.phikal.regex (pid 5130) has died
11-30 20:41:34.732   877  2966 D ActivityManager: cleanUpApplicationRecord -- 5130
11-30 20:41:34.748   877  2966 I ActivityManager: Start proc 5149:com.phikal.regex/u0a40 for activity com.phikal.regex/.Activities.GameActivity
11-30 20:41:35.256  5149  5149 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10040 <<<<<<
11-30 20:41:35.262  5149  5149 D AndroidRuntime: CheckJNI is OFF
11-30 20:41:35.320  5149  5149 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
11-30 20:41:35.385  5149  5149 I Radio-JNI: register_android_hardware_Radio DONE
11-30 20:41:35.421  5149  5149 D AndroidRuntime: Calling main entry com.android.internal.os.ExecInit
11-30 20:41:35.422  5149  5149 D Zygote  : begin preload
11-30 20:41:35.422  5149  5149 I Zygote  : Preloading classes...
11-30 20:41:35.521  5149  5149 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
11-30 20:41:35.524  3265  3265 I ServiceManager: Waiting for service AtCmdFwd...
11-30 20:41:35.542  5149  5149 I Zygote  : ...preloaded 1 classes in 119ms.
11-30 20:41:35.542  5149  5149 I art     : VMRuntime.preloadDexCaches starting
11-30 20:41:35.599  5149  5149 I art     : VMRuntime.preloadDexCaches strings total=282285 before=37887 after=37887
11-30 20:41:35.599  5149  5149 I art     : VMRuntime.preloadDexCaches types total=23482 before=2491 after=3283
11-30 20:41:35.599  5149  5149 I art     : VMRuntime.preloadDexCaches fields total=111399 before=8045 after=13418
11-30 20:41:35.599  5149  5149 I art     : VMRuntime.preloadDexCaches methods total=196726 before=14964 after=28649
11-30 20:41:35.599  5149  5149 I art     : VMRuntime.preloadDexCaches finished
11-30 20:41:35.611  5149  5149 I Zygote  : Preloading resources...
11-30 20:41:35.751  5149  5149 I Zygote  : ...preloaded 114 resources in 140ms.
11-30 20:41:35.756  5149  5149 I Zygote  : ...preloaded 41 resources in 6ms.
11-30 20:41:35.756  5149  5149 I Zygote  : Preloading shared libraries...
11-30 20:41:35.765  5149  5149 D Zygote  : end preload
11-30 20:41:35.766  5149  5149 I SamplingProfilerIntegration: Profiling disabled.
11-30 20:41:35.842  5149  5149 W System  : ClassLoader referenced unknown path: /data/app/com.phikal.regex-1/lib/arm64
11-30 20:41:35.933  5149  5149 D AndroidRuntime: Shutting down VM
11-30 20:41:35.935  5149  5149 E AndroidRuntime: FATAL EXCEPTION: main
11-30 20:41:35.935  5149  5149 E AndroidRuntime: Process: com.phikal.regex, PID: 5149
11-30 20:41:35.935  5149  5149 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.phikal.regex/com.phikal.regex.Activities.GameActivity}: java.lang.IndexOutOfBoundsException: setSpan (5 ... 5) ends beyond length 0
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3401)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3441)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2714)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6080)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:68)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: Caused by: java.lang.IndexOutOfBoundsException: setSpan (5 ... 5) ends beyond length 0
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1265)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:677)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at android.text.Selection.setSelection(Selection.java:76)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at android.widget.EditText.setSelection(EditText.java:96)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at com.phikal.regex.Activities.GameActivity.onResume(Unknown Source)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6768)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3378)
11-30 20:41:35.935  5149  5149 E AndroidRuntime: 	... 12 more
11-30 20:41:35.936  5149  5149 E AndroidRuntime: Error reporting crash
11-30 20:41:35.936  5149  5149 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
11-30 20:41:35.936  5149  5149 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
11-30 20:41:35.936  5149  5149 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:615)
11-30 20:41:35.936  5149  5149 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5103)
11-30 20:41:35.936  5149  5149 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
11-30 20:41:35.936  5149  5149 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
11-30 20:41:35.936  5149  5149 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
11-30 20:41:35.936  5149  5149 I Process : Sending signal. PID: 5149 SIG: 9
11-30 20:41:35.962   877   903 I ActivityManager: Process com.phikal.regex (pid 5149) has died
11-30 20:41:35.962   877   903 D ActivityManager: cleanUpApplicationRecord -- 5149
11-30 20:41:35.974   541  5153 I art     : Starting a blocking GC HeapTrim
11-30 20:41:35.985   877   903 I ActivityManager: Start proc 5168:com.phikal.regex/u0a40 for activity com.phikal.regex/.Activities.GameActivity
```

**Comment by phikal** [comment]
Could this be related to #31? The `IndexOutOfBoundsException` seems fishy to me, especially after having have had such a bug just one day ago. What commit (if any) is this build based on?

And when you clear apl data, restart the app twice, does the same happen again? If yes, could you provide the preference file (`/data/data/com.phikal.regex/...`)?

**Comment by dark159123** [comment]
It is version 1.3 from the f-droid repo, which was build on 2016-11-01, so it might be fixed now.
Clearing app data, fixes the issue, and i am not able to replicate again. I will update if i successfully do so again.

**Comment by phikal** [comment]
Any updates?

**Comment by dark159123** [comment]
I can no longer replicate the issue, i assume it's fixed.
